# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Evaluate Portability to .Net Core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  job_1:
    name: BootStrap - compatability Evaluator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install Upgrade Assistant
      run: dotnet tool install -g --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources upgrade-assistant       
    - name: Install JQ
      run: chocolatey install jq -y

  job_2:
    name: Execute Upgrade-assistant
    runs-on: windows-latest
    steps:
    - name: Evaluate Upgrade-assistant
      run: upgrade-assistant.exe analyze .\SimpleFrameworkApp.sln -t LTS
    - name: Extract evaluation results
      run: jq '[.runs[].results[] | select(.locations[].physicalLocation.region.startLine != null) | {ruleId:.ruleId,message:.message.text, filePath:.locations[].physicalLocation.artifactLocation.uri,lineNumber:.locations[].physicalLocation.region.startLine}]' .\AnalysisReport.sarif > .\new_baseline.json
    - name: Execute Powershell script to evaluate results
      shell: pwsh
      run: |
        ./.github/workflows/Evaluator.ps1      
    - name: Archive upgrade-analyis results
      uses: actions/upload-artifact@v3
      with:
        name: ua-analyze-report
        path: ./new_baseline.json        
